# courses_data.py
# Static course catalog used by the Python analytics module.
# In a real system this would come from a shared database.
# Kept separate so it can be reused across modules.

COURSE_CATALOG = [
    {
        "course_id": "CPS101",
        "title": "Intro to Programming",
        "department": "COMPUTER_SCIENCE",
        "credit_hours": 3,
        "prerequisites": [],
        "tags": ["beginner", "programming", "fundamentals"],
        "difficulty": 1,
    },
    {
        "course_id": "CPS201",
        "title": "Data Structures",
        "department": "COMPUTER_SCIENCE",
        "credit_hours": 3,
        "prerequisites": ["CPS101"],
        "tags": ["algorithms", "data-structures", "programming"],
        "difficulty": 2,
    },
    {
        "course_id": "CPS301",
        "title": "Algorithms & Complexity",
        "department": "COMPUTER_SCIENCE",
        "credit_hours": 3,
        "prerequisites": ["CPS201"],
        "tags": ["algorithms", "complexity", "advanced"],
        "difficulty": 3,
    },
    {
        "course_id": "CPS314",
        "title": "Programming Languages",
        "department": "COMPUTER_SCIENCE",
        "credit_hours": 3,
        "prerequisites": ["CPS101", "CPS201"],
        "tags": ["languages", "paradigms", "theory"],
        "difficulty": 3,
    },
    {
        "course_id": "CPS401",
        "title": "Software Engineering",
        "department": "COMPUTER_SCIENCE",
        "credit_hours": 3,
        "prerequisites": ["CPS201", "CPS314"],
        "tags": ["engineering", "design", "advanced"],
        "difficulty": 4,
    },
    {
        "course_id": "CPS410",
        "title": "Compiler Design",
        "department": "COMPUTER_SCIENCE",
        "credit_hours": 3,
        "prerequisites": ["CPS314"],
        "tags": ["compilers", "languages", "theory"],
        "difficulty": 4,
    },
    {
        "course_id": "MTH101",
        "title": "Calculus I",
        "department": "MATHEMATICS",
        "credit_hours": 4,
        "prerequisites": [],
        "tags": ["mathematics", "calculus", "fundamentals"],
        "difficulty": 2,
    },
    {
        "course_id": "MTH201",
        "title": "Discrete Mathematics",
        "department": "MATHEMATICS",
        "credit_hours": 3,
        "prerequisites": ["MTH101"],
        "tags": ["mathematics", "logic", "theory"],
        "difficulty": 2,
    },
    {
        "course_id": "CPS320",
        "title": "Operating Systems",
        "department": "COMPUTER_SCIENCE",
        "credit_hours": 3,
        "prerequisites": ["CPS201"],
        "tags": ["systems", "concurrency", "advanced"],
        "difficulty": 3,
    },
    {
        "course_id": "CPS350",
        "title": "Database Systems",
        "department": "COMPUTER_SCIENCE",
        "credit_hours": 3,
        "prerequisites": ["CPS201"],
        "tags": ["databases", "sql", "data"],
        "difficulty": 3,
    },
]
